Repository fga-eps-mds/2022-2-Alectrion-EquipamentApi, pull requests merged in 2022-12, with the labels that each got.

#1 Atualização do README: repo Equipament API
  README.md
Labels: documentation

#2 Continuous Deployment
  .github/workflows/service-deploy.yml
  README.md
  src/db/config.ts
Labels: bug, documentation

#3 Us/06 cadastro equipamentos
  src/db/migrations/1664153249772-default.ts
  src/domain/entities/equipamentEnum/status.ts
Labels: MDS, US
